/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tema9;

/**
 *
 * @author alumno
 */
public class Ejemplo1 extends javax.swing.JPanel {

    /**
     * Creates new form Ejemplo1
     */
    public Ejemplo1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MUSICA = new javax.swing.JButton();
        DEPORTES = new javax.swing.JButton();
        RESET = new javax.swing.JButton();
        RESULTADO = new javax.swing.JTextField();
        AFICIONES = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        MUSICA.setBackground(new java.awt.Color(0, 102, 102));
        MUSICA.setText("MUSICA");
        MUSICA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MUSICAMouseClicked(evt);
            }
        });

        DEPORTES.setBackground(new java.awt.Color(0, 102, 102));
        DEPORTES.setText("DEPORTES");
        DEPORTES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DEPORTESMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DEPORTESMousePressed(evt);
            }
        });

        RESET.setForeground(new java.awt.Color(51, 255, 153));
        RESET.setText("RESET");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });

        RESULTADO.setText("RESULTADO");

        AFICIONES.setBackground(new java.awt.Color(0, 102, 102));
        AFICIONES.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AFICIONES.setForeground(new java.awt.Color(0, 0, 0));
        AFICIONES.setText("AFICIONES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(MUSICA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DEPORTES)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RESULTADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RESET)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(AFICIONES)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MUSICA)
                    .addComponent(DEPORTES))
                .addGap(18, 18, 18)
                .addComponent(AFICIONES)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(RESULTADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(RESET)
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RESETActionPerformed

    private void MUSICAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MUSICAMouseClicked
        // TODO add your handling code here:
        this.RESULTADO.setText("MUSICA");
    }//GEN-LAST:event_MUSICAMouseClicked

    private void DEPORTESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DEPORTESMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DEPORTESMouseClicked

    private void DEPORTESMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DEPORTESMousePressed
        // TODO add your handling code here:
        this.RESULTADO.setText("DEPORTES");
    }//GEN-LAST:event_DEPORTESMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AFICIONES;
    private javax.swing.JButton DEPORTES;
    private javax.swing.JButton MUSICA;
    private javax.swing.JButton RESET;
    private javax.swing.JTextField RESULTADO;
    // End of variables declaration//GEN-END:variables
}
